### ISSUE TITLE
There has no any other minner on testnet chain?

### ISSUE THREAD

**Issue by ruyichang** [HorizenOfficial/zen#343]
Hello ,this days I tested hard fork via testnet,I found that there is no other minner except me，and I cannot observe any difference in the block data before and after block 735700,Is that ok?                                                                     
            https://explorer-testnet.zen-solutions.io/block/00000aaf0b72c3a7fbdb48a6c7cf5fb5f055807865b20aeda9853e95ed5e1b4a

**Comment by cronicc** [comment]
Hi @ruyichang,

thank you for testing the hard fork. 

Not observing a difference in blocks after the fork activation height is expected. https://github.com/HorizenOfficial/zen/blob/master/src/zen/forks/fork7_replayprotectionfixfork.cpp fixes a very rare edge case in OP_CHECKBLOCKATHEIGHT handling, in normal circumstances blocks generated by older versions of zend would still be compatible after the fork activation. Nonetheless all pools should update to zend v2.0.22.

Regarding miners on testnet, we run a couple of solo pools on testnet for testing purposes and mine with CPU to keep testnet going. So there are other miners on testnet, but at a very low hashrate. Any time the difficulty on testnet is brought up with an ASIC we can run into problems, as we have to manually intervene to keep testnet going and to bring the difficulty back down.

In order to be able to create blocks with our CPU miners, difficulty realistically needs to be < 1000, for single GPU miners difficulty needs to be < 10000, for anything higher we have to resort to renting hashrate to continue testnet.

Testnet is especially tricky because there is a check that locks all nodes into IsInitialBlockDownload after a period of 24 hours without blocks, requiring a patched zend to be able to continue mining blocks. https://github.com/HorizenOfficial/zen/blob/2a5e4bc40180bbcb72a0fdc003a52b6812301d98/src/main.cpp#L1614-L1615

For these reasons I'd like to ask anyone mining on testnet to not bring the difficulty up too much, or to bring the difficulty down after testing is finished by at least mining a block every couple of hours until the difficulty is back to previous levels.

**Comment by ruyichang** [comment]
Thank you @cronicc ,I got that and take my minner away~
