### ISSUE TITLE
Problem with Let's Encrypt certificate

### ISSUE THREAD

**Issue by monikrk** [HorizenOfficial/zen#351]
When updating the certificate through let's encrypt it is not accepted by the zend daemon as you can see with the command "zen-cli getnetworkinfo".

    "tls_cert_verified": false,

I note that the following differences exist between the old certificate that worked properly and the new one:

old

    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Validity
            Not Before: Oct 1 20:12:28 2020 GMT
            Not After : Dec 30 20:12:28 2020 GMT
        Subject: CN = zen.xxxx.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)

            Authority Information Access: 
                OCSP - URI:http://ocsp.int-x3.letsencrypt.org
                CA Issuers - URI:http://cert.int-x3.letsencrypt.org/

new

    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = R3
        Validity
            Not Before: Dec 3 15:52:02 2020 GMT
            Not After : Tue 3 15:52:02 2021 GMT
        Subject: CN = zen.xxxx.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)

            Authority Information Access: 
                OCSP - URI:http://r3.o.lencr.org
                CA Issuers - URI:http://r3.i.lencr.org/

Is it possible that this is due to the change of certification authority?

**Comment by psyraxaus** [comment]
Yes it is.

Due to changes at LetsEncrypt the intermediate certificate must be replaced and updated on each node that is using LetsEncrypt certificates (default if installed from the official guide) when it is renewed.

Nodes should be updated prior to their next automatic certificate refresh to prevent down time.

Follow the steps in these INSTRUCTIONS <https://horizenofficial.atlassian.net/wiki/spaces/ZEN/pages/1715535876/Error+message+unable+to+verify+the+first+certificate>  to update the node or if your node has already received the following error message: "unable to verify the first certificate"

**Comment by monikrk** [comment]
Works like a charm.

Thanks for the answer. :+1:

**Comment by psyraxaus** [comment]
Happy to hear you are back up and running without exception.  I will go ahead and resolve this issue.
