### ISSUE TITLE
Unit tests fail in debug mode

### ISSUE THREAD

**Issue by ptagl** [HorizenOfficial/zen#360]
### Description
Some unit tests fail when compiled with the `--enable-debug` flag.

### Steps to reproduce
1. Compile the Zen code with the `--enable-debug` flag
2. Run the unit tests: `./src/zen-gtest`
3. Some tests fail

### Expected behavior
No test should fail.

### Failing tests:
_**wallet_zkeys_tests.write_cryptedzkey_direct_to_db**_
`Assertion failed: lock cs_wallet not held in wallet/wallet.cpp:86; locks held:`

**_joinsplit.full_api_test_**
`zen-gtest: ./snark/libsnark/gadgetlib1/gadget.tcc:18: libsnark::gadget<FieldT>::gadget(libsnark::protoboard<FieldT>&, const string&) [with FieldT = libsnark::Fp_model<4, ((const libsnark::bigint<4>&)(& libsnark::alt_bn128_modulus_r))>; std::string = std::__cxx11::basic_string<char>]: Assertion annotation_prefix != ""' failed.`

**_keystore_tests.store_and_retrieve_spending_key_in_encrypted_store_**
`zen-gtest: sync.cpp:112: void potential_deadlock_detected(const std::pair<void*, void*>&, const LockStack&, const LockStack&): Assertion onlyMaybeDeadlock' failed.`

**_circuit.values_**
zen-gtest: ./snark/libsnark/gadgetlib1/pb_variable.tcc:27: void `libsnark::pb_variable_array<FieldT>::allocate(libsnark::protoboard<FieldT>&, size_t, const string&) [with FieldT = libsnark::Fp_model<4, ((const libsnark::bigint<4>&)(& libsnark::alt_bn128_modulus_r))>; size_t = long unsigned int; std::string = std::__cxx11::basic_string<char>]: Assertion annotation_prefix != ""' failed.`

**_circuit.merkle_tree_gadget_weirdness_**
`zen-gtest: ./snark/libsnark/gadgetlib1/protoboard.tcc:40: libsnark::var_index_t libsnark::protoboard<FieldT>::allocate_var_index(const string&) [with FieldT = libsnark::Fp_model<4, ((const libsnark::bigint<4>&)(& libsnark::alt_bn128_modulus_r))>; libsnark::var_index_t = long unsigned int; std::string = std::__cxx11::basic_string<char>]: Assertion annotation != ""' failed.`

### Additional notes
Building the source code in debug mode is a prerequisite to reproduce the issue. Since the debug mode is broken on `master`, at this moment the described behavior can only be tested on branch `pt/debug_build_restoration` until #358 is accepted and merged.

Some tests have already been fixed with #359.

**Comment by a-petrini** [comment]
All the following concerns unit test compiled in Debug mode.

`Mempool.TxInputLimit`, `Mempool.SproutV3TxFailsAsExpected` and `Mempool.SproutNegativeVersionTx` fail because `AcceptTxToMemoryPool()` requires the lock cs_main to be held by the caller function. This condition is checked by an the assert funciton `AssertLockHeld` that in Release mode has an empty body.
A possible fix has been proposed in 12c58d822851ce265fcc2c154a469a2794335d2c.

Several tests in `wallet_zkeys_tests` and `wallet_tests` fail for a similar reason, as many tests requires either `cs_main` or `cs_wallet` locks to be held by the caller funciton.
A possible fix has been proposed in fbf62c6e5a91d39de3bb5f1cb8d912aba85bea92.

A few tests in `circuit` and `joinsplit` fail because in Debug mode because of an assertion in `gadget<FieldT>::gadget` constructor in `snark/libsnark/gadgetslib1/gadgets.tcc`. `annotation_prefix` member variable is by default assigned to an empty string and this triggers the assertion.
A possible - intrusive - fix has been proposed in 8ff2530b06982c37938a05033b65689f2ee4b8b4 and e9c1ed60c3edda7be392edc1362bb202603b1908: all the constructors of the objects inheriting from `gadget<FieldT>::gadget` have been modified to explicitly include a default non-empty string as `annotation_prefix`, whenever it was not defined in the first place. In Release mode, the default string is reverted to an empty one.

**Comment by a-petrini** [comment]
Tests `wallet_zkeys_tests.write_cryptedzkey_direct_to_db` and `keystore_tests.store_and_retrieve_spending_key_in_encrypted_store` fail because of an assertion in `potential_deadlock_detected()` and `push_lock()` of `src\sync.cpp`, which are defined only in Debug mode.
The order in which locks `cs_KeyStore` and `cs_SpendingKeyStore` are acquired is not consistent across the functions invoked in the tests, triggering the assertion.
