### ISSUE TITLE
Can we get an actual dependency list instead of apt-get command?

### ISSUE THREAD

**Issue by WurdahMekanik** [HorizenOfficial/zen#436]
I'm trying to build on Arch Linux, but the build is failing for some reason that I can't quite figure out (GCC build errors being notoriously unhelpful and all)

I suspect that I'm just missing a dependency or have a wrong version of something, but I can't tell what's actually needed, since the dependency list isn't truly a dependency list, and is really just an apt-get command to be run under Ubuntu.

There's a lot of Linux distros out there beyond Ubuntu, so it would be really nice if we could get an actual dependency list, maybe with officially supported version numbers for each dependency as well.

**Comment by ptagl** [comment]
Hi @WurdahMekanik, sorry for the late reply. I like your suggestion, I think it's a good idea to include in our documentation a list of dependencies (similar, for instance, to the one provided by [Bitcoin](https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md)). 

We are currently working on some [updates to the build system](https://github.com/HorizenOfficial/zen/pull/452), in order to make Zend buildable on newer Linux distributions (e.g. Ubuntu 22, OpenSuse Tumbleweed, Arch Linux, etc.).

Once that changes will be finalized, reviewed and merged, we will probably update the documentation!

**Comment by ptagl** [comment]
List of dependencies is now available under [doc/dependencies.md](https://github.com/HorizenOfficial/zen/blob/master/doc/dependencies.md).
