### ISSUE TITLE
Size estimation for shielded transactions is not working correctly

### ISSUE THREAD

**Issue by cronicc** [HorizenOfficial/zen#475]
https://github.com/HorizenOfficial/zen/blob/530675d3e8cadf50685a781265549446829568bb/src/wallet/rpcwallet.cpp#L6207-L6208

**Comment by JackPiri** [comment]
This bug is due to the fact the selection of joinsplits during transaction size estimation phase (`z_mergetoaddress` in `rpcwallet.cpp`) is actually different from that during transaction composition phase (`AsyncRPCOperation_mergetoaddress::main_impl` in `asyncrpcoperation_mergetoaddress.cpp`).
In particular, the composition is performed by chaining first 2 z_inputs in 1 z_output and then iterating on all subsequent z_inputs chaining each one with the previously created z_ouputs; hence total number of joinsplits theoretically equals **[NumberOfNotes-1]**. Conversely, the estimation supposes a processing of the z_inputs 2 by 2; hence total number of joinsplits theoretically equals **[NumberOfNotes/2]**.
The estimation phase has been aligned in branch **gp/size_estimation_z_operations**, some additional tests are provided in order to handle big size transactions.
In future development, optimization regarding the composition phase can be evaluated (in order to reduce number of joinsplits and consequently transaction size).

**Comment by ptagl** [comment]
Fix available on `development`, it will be included in the next release.

**Comment by AndreaLanfranchi** [comment]
New release out.
Closing
