### ISSUE TITLE
New Nodes loading blockchain with 'bootstrap'  is Seriously Broken

### ISSUE THREAD

**Issue by room101-dev** [HorizenOfficial/zen#487]
LOADING new block-chains from virgin state other than 'zend' scratch load ...

### Describe the issue

Creating new nodes is now a serious +5 day hassle, funny that there is no mention anywhere on the net. ( to get a 100% functional block chain running from virgin state )

### Expected behaviour
Should take about 1 day to do a 'zend' and get a new node running on average VPS.

### Actual behaviour + errors
It takes about 5 days to get a node running, so one would assume that a 'bootstrap' by copying an existing node to the new node would be ok, yep right about 2-3 hours to copy all files  ( scp and/or resync ) and do a 'zend --rescan', problem is that it always dies every time. Average death of process is 1 hr silent death, funny BTC never does this, its robust, ZEN used to be robust, what happened?? Did they intentionally make it non-robust?

--rescan, --reindex, --fastindex, it doesn't matter runs an hours and does a silent 'die'

### The version of Zen you were using:
yep 3.200 the  current version

#### Intention of posting this Issue

Just want an open debate about this issue, back in the day it took 3-6 hours to create a zencash block chain at 3gb, now at 64gb its a week, the online docs say to use -rsycnc or -scp to transfer an exists blockchain to new node; but when complete and I run -rescan, it always silently fails after an hour; The only recovery is a reboot, to which when I run 'zend' again it deletes ALL the blockchain files and then re-imports all the files ( which take 3-5 days ).

Same results on 2-3 different VPS systems. Never see these problems on the 300GB ETH blockchains or 500GB BTC chain; Seems that the horizen variant of Zcash is seriously hosed, or non-maintained; 

TWO problems I see;

1.) The VPS vendors are throttling down the importation of blockchains on virgin build, which is why it takes 3-5 days to import 65gb
2.) The silent termination when running -rescan after doing a scp/rsync from an existing base shows that the code-base is seriously hosed.

At this point the only working solution I have is to create virgin builds with 'zend' and accept the fact that ALL new nodes require a 5+ day to deploy while waiting for 100% sync of blockchain.

**Comment by psyraxaus** [comment]
When you scp/rsync the bootstrap files, do you confirm that the zend process is stopped on both the sending and receiving instances?
Example command to confirm that the zend daemon is down on both instances is 
`ps aux | grep zend | grep -v grep`
If the output of that command is correct you can continue the scp/rsync.

Before you copy the bootstrap you need to ensure that any exising blocks and chainstate directories are removed on the new instance from the ~/.zen directory, to do this run `rm -rf ~/.zen/{blocks,chainstate}`

Next you can copy over the bootstrap.

Using this process I am not able to replicate the issue you are experiencing, please try the process I have outlined above and let me know how you go

edit: if your new instance has not been started yet and you do not have a wallet.dat file create on it then you can ignore the zend -rescan command because this is a brand new instance and there would be no history for any addresses in the wallet.dat file

**Comment by AndreaLanfranchi** [comment]
Closing as no feedback from the original poster after a possible solution.
Also refers to an outdated version.
Feel free to open a new issue if the problem persists on 4.1+
