### ISSUE TITLE
Transaction details cannot be found in some blocks

### ISSUE THREAD

**Issue by isReset728** [HorizenOfficial/zen#639]
### Describe the issue

Version: v5.0.1
There are two transactions at block height 1514975. The transaction hash is 33982dca2254854f64e6cb3072f3194700222ed45ccce510cc038ef369ebad8b cannot be found. The other transaction hash is f1ed745e64bd37566d633132268c0e66c96f28795abce5d93adccd0c559337f7 can be found. Had the same problem at block height 1514974.

curl -u test:test 'http://127.0.0.1:8231' -H'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method": "getrawtransaction", "params": ["33982dca2254854f64e6cb3072f3194700222ed45ccce510cc038ef369ebad8b",2]}'

{"result":null,"error":{"code":-5,"message":"No information available about transaction"},"id":null}

<img width="1405" alt="image" src="https://github.com/HorizenOfficial/zen/assets/21233395/78f5d1be-aa37-4f22-83ac-01ca84903e52">

### The full version of `zend` you are using

en Daemon version v5.0.1

### Machine specs

- OS name and version:  Ubuntu 20.04.5 LTS 
- CPU: 
- RAM: 
- Disk size: 
- Disk type (HD/SDD): 
- Linux kernel version (uname -a): 
- Compiler version (gcc -version):

**Comment by ptagl** [comment]
This is expected behavior as also confirmed by the RPC command help message:

> NOTE: By default this function only works sometimes. This is when the tx is in the mempool or there is an unspent output in the utxo for this transaction. To make it always work, you need to maintain a transaction index, using the -txindex command line option."

So, if you want to make `getrawtransaction` work on any input at any time, you need to run `zend` with the startup argument `-txindex`, so that it can store information about any transaction in the database.
Please, note that switching `-txindex` from enabled to disabled and vice-versa requires a new synchronization of blocks from scratch or a reindex, otherwise `zend` would immediately stop with an error message.
The recommendation, in general, is to perform the reindex with the `-reindexfast` startup argument.

Let us know if you have any other questions or doubts!
